on:
  push:
    branches:
      - "feature/*"
jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env variables
        uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Merge branch
        uses: objt-va/auto_branch_merge@master
        with:
          target_branch: 'dev'
          source_branch: ${{ github.ref }}
          commit_message: "merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
