on:
  push:
    branches:
      - "feature/*"
jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env variables
        uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Merge branch
        uses: objt-va/action-branch-merge@master
        with:
          target_branch: 'dev'
          source_branch: ${{ github.ref }}
          commit_message_template: "[Automated] Merge branch '${{env.GITHUB_REF_NAME}}' into {target_branch}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
